# -*- coding: utf-8 -*-
"""streetleague_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAVviwiqb-2aDMHAtmYi_IhAS8tzYw-o
"""

import pandas as pd
import numpy as np
import joblib
import warnings
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

warnings.filterwarnings('ignore')

print("="*60)
print(" ÉTAPE 1 : CHARGEMENT & NETTOYAGE DES DONNÉES")
print("="*60)

# 1. Chargement (Structure identique à votre DB Spring Boot)
df = pd.read_csv("realistic_interactions.csv")
products = pd.read_csv("realistic_products.csv")

# Nettoyage basique (suppression doublons, valeurs nulles, quantités <= 0)
df = df.drop_duplicates(subset=['user_id', 'product_id'])
df = df[df['quantity'] > 0]
df = df.dropna(subset=['user_id', 'product_id'])

print(f"✅ Données brutes : {len(df)} interactions valides")
print(f"👥 Utilisateurs uniques : {df['user_id'].nunique()}")
print(f"📦 Produits uniques     : {df['product_id'].nunique()}")

print("\n" + "="*60)
print("🔄 ÉTAPE 2 : FEATURE ENGINEERING (Matrice User × Product)")
print("="*60)

# Création de la matrice d'interactions (Lignes=Users, Colonnes=Produits, Valeurs=Quantité)
user_ids = sorted(df['user_id'].unique())
prod_ids = sorted(df['product_id'].unique())

pivot = df.pivot_table(index='user_id', columns='product_id', values='quantity', fill_value=0)
pivot = pivot.reindex(index=user_ids, columns=prod_ids, fill_value=0)

print(f"📐 Matrice créée : {pivot.shape[0]} utilisateurs × {pivot.shape[1]} produits")
print(f"📊 Densité de la matrice : {(pivot.astype(bool).sum().sum() / (pivot.shape[0]*pivot.shape[1])):.2%}")

print("\n" + "="*60)
print("🤖 ÉTAPE 3 : SPLIT & ENTRAÎNEMENT (Analogie PDF: 'Écrire le code métier')")
print("="*60)

# Split 80/20 pour validation
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

# Reconstruction matrice d'entraînement uniquement
pivot_train = train_df.pivot_table(index='user_id', columns='product_id', values='quantity', fill_value=0)
pivot_train = pivot_train.reindex(index=user_ids, columns=prod_ids, fill_value=0)

# Normalisation (améliore la similarité cosinus)
scaler = StandardScaler(with_mean=False)
X_train = scaler.fit_transform(pivot_train)

# Entraînement du modèle KNN (Collaborative Filtering)
model = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=6)
model.fit(X_train)
print("✅ Modèle entraîné (NearestNeighbors - Cosine Similarity)")

print("\n" + "="*60)
print("📊 ÉTAPE 4 : ÉVALUATION (Analogie PDF: 'Executer les tests unitaires')")
print("="*60)

def evaluate_recommender(model, X_train, pivot_train, test_df, K=5):
    """Calcule Precision@K, Recall@K, HitRate et Coverage"""
    hits = 0
    total_precision = 0
    total_recall = 0
    total_test_users = 0
    recommended_products = set()

    test_users = test_df['user_id'].unique()

    for uid in test_users:
        if uid not in pivot_train.index:
            continue

        u_idx = list(pivot_train.index).index(uid)
        user_vec = X_train[u_idx].reshape(1, -1)

        # Trouver les K voisins les plus similaires
        _, sim_idxs = model.kneighbors(user_vec, n_neighbors=K+1)
        neighbor_data = X_train[sim_idxs[0][1:]]  # [1:] exclut l'utilisateur lui-même

        # Agrégation des scores
        scores = np.sum(neighbor_data, axis=0)

        # Masquer les produits déjà achetés en train
        bought_mask = user_vec.flatten() > 0
        scores[bought_mask] = -np.inf

        # Top K recommandations
        top_idxs = np.argsort(scores)[::-1][:K]
        recs = pivot_train.columns[top_idxs].tolist()
        recommended_products.update(recs)

        # Produits réellement achetés dans le test set
        actuals = set(test_df[test_df['user_id']==uid]['product_id'])
        if not actuals: continue

        # Métriques
        relevant = len(set(recs) & actuals)
        total_precision += relevant / K if K > 0 else 0
        total_recall += relevant / len(actuals) if len(actuals) > 0 else 0
        hits += 1 if relevant > 0 else 0
        total_test_users += 1

    precision_at_k = total_precision / total_test_users if total_test_users > 0 else 0
    recall_at_k = total_recall / total_test_users if total_test_users > 0 else 0
    hit_rate = hits / total_test_users if total_test_users > 0 else 0
    coverage = len(recommended_products) / len(prod_ids) if len(prod_ids) > 0 else 0

    return {
        "Precision@K": precision_at_k,
        "Recall@K": recall_at_k,
        "HitRate@K": hit_rate,
        "Coverage": coverage,
        "K": K,
        "TestUsers": total_test_users
    }

metrics = evaluate_recommender(model, X_train, pivot_train, test_df, K=5)

print("📈 RÉSULTATS D'ÉVALUATION (Tests unitaires du modèle) :")
print(f"   • Precision@{metrics['K']} : {metrics['Precision@K']:.2%} (Produits recommandés pertinents)")
print(f"   • Recall@{metrics['K']}    : {metrics['Recall@K']:.2%} (Historique test récupéré)")
print(f"   • HitRate@{metrics['K']}   : {metrics['HitRate@K']:.2%} (Au moins 1 bonne recommandation)")
print(f"   • Coverage           : {metrics['Coverage']:.2%} (Diversité du catalogue suggéré)")
print(f"   • Utilisateurs testés: {metrics['TestUsers']}")

print("\n💡 Note Ingénierie : En recommandation, on n'utilise pas l'Accuracy classique.")
print("   Precision@K & Recall@K sont les équivalents 'tests unitaires' du PDF.")

print("\n" + "="*60)
print("💾 ÉTAPE 5 : SAUVEGARDE (Analogie PDF: 'Compiler/créer un .jar')")
print("="*60)

joblib.dump((model, pivot_train.index.tolist(), pivot_train.columns.tolist(), scaler, X_train), "recommender.joblib")
print("✅ recommender.joblib généré avec succès !")
print("   📦 Ce fichier = notre 'fonction compilée' prête pour FastAPI.")

print("\n" + "="*60)
print("🔮 ÉTAPE 6 : TEST D'INFÉRENCE (Analogie PDF: 'Instancier et appeler une méthode')")
print("="*60)

def predict_for_user(user_id, top_k=4, exclude_ids=None):
    """Simulation de l'appel .predict() côté API"""
    if user_id not in pivot_train.index:
        return {"user_id": user_id, "recommendations": prod_ids[:top_k], "note": "Cold Start (fallback popularité)"}

    u_idx = list(pivot_train.index).index(user_id)
    user_vec = X_train[u_idx].reshape(1, -1)
    _, sim_idxs = model.kneighbors(user_vec, n_neighbors=top_k+1)

    neighbor_data = X_train[sim_idxs[0][1:]]
    scores = np.sum(neighbor_data, axis=0)

    bought = np.where(user_vec.flatten() > 0)[0]
    scores[bought] = -np.inf
    if exclude_ids:
        for pid in exclude_ids:
            if pid in prod_ids:
                scores[list(prod_ids).index(pid)] = -np.inf

    top_idxs = np.argsort(scores)[::-1][:top_k]
    recs = [prod_ids[i] for i in top_idxs]
    return {"user_id": user_id, "recommendations": recs}

test_uid = np.random.choice(user_ids)
result = predict_for_user(test_uid, top_k=4)
print(f" Test d'inférence pour User #{test_uid} :")
print(f"   📦 Recommandations IDs : {result['recommendations']}")
print("✅ Pipeline ML complet validé. Prêt pour l'exposition FastAPI.")

