# -*- coding: utf-8 -*-
"""generate_realistic_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpK9xGu6FaQhwNIIAtfTaXLh8_ll_eCW
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

np.random.seed(42)
random.seed(42)

print("📦 Génération de données réalistes structurées comme votre DB...")

# 1. Métadonnées produits (simule votre table `materiel`)
products = pd.DataFrame({
    "product_id": list(range(1, 21)),  # 20 produits réels (IDs 1-20)
    "name": [f"Produit_{i}" for i in range(1, 21)],
    "category_id": np.random.choice([1, 2, 3, 4, 5], 20),
    "price": np.random.uniform(20, 150, 20).round(2),
    "is_active": True
})

# 2. Profils utilisateurs avec préférences cachées (simule `user` + historique)
n_users = 150
user_prefs = {
    i: {
        "fav_cat": np.random.choice([1, 2, 3, 4, 5]),  # Catégorie préférée
        "activity_level": np.random.uniform(0.3, 1.0)   # Fréquence d'achat
    }
    for i in range(1, n_users + 1)
}

# 3. Génération des interactions (simule `ligne_commande` + `commande`)
interactions = []
start_date = datetime(2025, 1, 1)

for uid in range(1, n_users + 1):
    prefs = user_prefs[uid]
    n_orders = int(np.random.poisson(prefs["activity_level"] * 8))  # 0 à ~15 commandes

    for _ in range(n_orders):
        # L'utilisateur achète 1 à 3 produits par commande
        n_items = np.random.randint(1, 4)

        # 70% de chance d'acheter dans sa catégorie préférée
        if random.random() < 0.7:
            candidate_prods = products[products["category_id"] == prefs["fav_cat"]]["product_id"].tolist()
        else:
            candidate_prods = products["product_id"].tolist()

        selected_prods = random.sample(candidate_prods, min(n_items, len(candidate_prods)))

        order_date = start_date + timedelta(days=random.randint(0, 365), hours=random.randint(8, 22))

        for pid in selected_prods:
            qty = np.random.choice([1, 2, 3], p=[0.6, 0.3, 0.1])
            price = products.loc[products["product_id"] == pid, "price"].values[0]

            interactions.append({
                "user_id": uid,
                "product_id": pid,
                "quantity": int(qty),
                "category_id": int(products.loc[products["product_id"] == pid, "category_id"].values[0]),
                "unit_price": float(price),
                "total_price": float(qty * price),
                "created_at": order_date.strftime("%Y-%m-%d %H:%M:%S")
            })

df_interactions = pd.DataFrame(interactions)

# 4. Export CSV (structure identique à votre DB)
df_interactions.to_csv("realistic_interactions.csv", index=False)
products.to_csv("realistic_products.csv", index=False)

print(f"✅ Dataset généré :")
print(f"   📊 {len(df_interactions)} interactions d'achat")
print(f"   👥 {df_interactions['user_id'].nunique()} utilisateurs")
print(f"    {df_interactions['product_id'].nunique()} produits")
print(f"   📁 Fichiers créés : realistic_interactions.csv, realistic_products.csv")
print(f"\n Exemple historique User 6 :")
user6 = df_interactions[df_interactions["user_id"] == 6]
print(f"   - {len(user6)} achats")
print(f"   - Catégories préférées : {user6['category_id'].value_counts().head(2).to_dict()}")
print(f"   - Produits fréquents : {user6['product_id'].value_counts().head(3).to_dict()}")

