spring.application.name=StreetLeague

### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/Streetleaguedb?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

### DATABASE CONNECTION POOL ###
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

### PERFORMANCE ###
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
# server.servlet.context-path=/StreetLeague
server.port=8086

##JWT
app.jwt.secret=MySuperSecretKeyForJwtAuthSpringSecurity2026!
app.jwt.expiration-ms=3600000

spring.security.oauth2.client.registration.google.client-id=600449644466-j1e4r3hdniufesa4vegcc02vijru1m0s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hamdisafa235@gmail.com
spring.mail.password=vuhw xrma cxqb wzjv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8
# URL du frontend Angular
app.frontend.url=http://localhost:4200