name: CI-CD Pipeline azure

on:
  push:
    branches: [ "deployement" ]

jobs:

  # =========================
  # 1. BACKEND BUILD
  # =========================
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Clean + Build Spring Boot
        run: |
          cd StreetLeague
          mvn clean package -DskipTests

      - name: Find JAR
        run: ls StreetLeague/target/

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: StreetLeague/target/*.jar


  # =========================
  # 2. FRONTEND BUILD
  # =========================
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd StreetLeagueFront
          npm install

      - name: Build Angular production
        run: |
          cd StreetLeagueFront
          npm run build -- --configuration production

      - name: Check dist output
        run: ls StreetLeagueFront/dist/


      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: StreetLeagueFront/dist/street-league-front


  # =========================
  # 3. DEPLOY TO AZURE
  # =========================
  deploy:
    needs: [backend, frontend]
    runs-on: ubuntu-latest

    steps:

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend


      # ================= Backend deploy
      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: streetleaguebackend
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: backend/*.jar


      # ================= Frontend deploy
      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: streetleaguefrontend
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
          package: frontend/street-league-front
         